name: Docker Image Specific CI

on:
  pull_request:
    branches:
      - master
    paths:
     - .github\workflows\docker-image.yml
     - Dockerfile
     - main.py
     - requirements.txt
     - specific.py
     - specific.requirements.txt
  push:
    branches:
      - master
    paths:
     - .github\workflows\docker-image.yml
     - Dockerfile
     - main.py
     - requirements.txt
     - specific.py
     - specific.requirements.txt
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker specific image
        run: |
          docker build --target specific -t mdlopresti/discord_messages:specific .
          docker push mdlopresti/discord_messages:specific
