name: Docker Image CI

on:
  pull_request:
    branches:
      - master
    paths:
     - specific.py
     - main.py
     - requirements.txt
     - Dockerfile
     - .github\workflows\docker-image.yml
  push:
    branches:
      - master
    paths:
     - specific.py
     - main.py
     - requirements.txt
     - Dockerfile
     - .github\workflows\docker-image.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build/Push the Docker notifier image
        run: |
          docker build --target notifier -t mdlopresti/scheduled_discord_messages:notifier -t mdlopresti/scheduled_discord_messages:latest .
          docker push mdlopresti/scheduled_discord_messages:notifier
          docker push mdlopresti/scheduled_discord_messages:latest

      - name: Build the Docker specific image
        run: |
          docker build --target specific -t mdlopresti/scheduled_discord_messages:specific .
          docker push mdlopresti/scheduled_discord_messages:specific
