name: Docker Image Notifier CI

on:
  pull_request:
    branches:
      - master
    paths:
     - .github\workflows\docker-image-notifier.yml
     - Dockerfile
     - main.py
     - requirements.txt
  push:
    branches:
      - master
    paths:
     - .github\workflows\docker-image-notifier.yml
     - Dockerfile
     - main.py
     - requirements.txt
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build/Push the Docker notifier image
        run: |
          docker build --target notifier -t mdlopresti/discord_messages:notifier -t mdlopresti/discord_messages:latest .
          docker push mdlopresti/discord_messages:notifier
          docker push mdlopresti/discord_messages:latest
