name: Send Messages

on:
  schedule:
    - cron: 0 16 * * 3
  workflow_dispatch:

jobs:
  config:
    runs-on: windows-latest
    outputs:
      FLESH_AND_STEEL_DATE: ${{ steps.next_session_dates.outputs.FLESH_AND_STEEL }}
      COVID_DATE: ${{ steps.next_session_dates.outputs.COVID }}
    steps:
      - id: next_session_dates
        name: Determine next session dates/times
        run: |
          $startdate = [datetime]"10/7/2020 00:00"
          Write-Host "start is $startdate"
          $nextsession = get-date -Hour 0 -Minute 0 -Second 0
          do {
            $nextsession = $nextsession.AddDays(1)
          } until ($nextsession.DayOfWeek -eq "Wednesday")

          Write-Host "The next wednesday is $nextsession"
          $time = New-TimeSpan -start $startdate -end $nextsession
          if (($time.Days/14) -match ".5") {
            $FleshAndSteel = $nextsession.ToString("yyyy MM dd")
            $Covid = $nextsession.addDays(7).ToString("yyyy MM dd")
            Write-Host "::set-output name=FLESH_AND_STEEL::$FleshAndSteel"
            Write-Host "::set-output name=COVID::$Covid"
          } else {
            $FleshAndSteel = $nextsession.addDays(7).ToString("yyyy MM dd")
            $Covid = $nextsession.ToString("yyyy MM dd")
            Write-Host "::set-output name=FLESH_AND_STEEL::$FleshAndSteel"
            Write-Host "::set-output name=COVID::$Covid"
          }
          Write-Host "FLESH_AND_STEEL_DATE = $FleshAndSteel"
          Write-Host "COVID_DATE = $Covid"

  notifications:
    needs: config
    runs-on: ubuntu-20.04
    steps:
      - name: send notification to flesh and steel
        shell: bash
        run: |
          echo "date is $${{ needs.jobs.config.outputs.FLESH_AND_STEEL_DATE }}"
          echo "time is $TIME"
          docker run -e WEBHOOK=$WEBHOOK -e NEXT_DATE="$${{ needs.jobs.config.outputs.FLESH_AND_STEEL_DATE }}" -e NEXT_TIME="$TIME" mdlopresti/scheduled_discord_messages:specific
        env:
          WEBHOOK: ${{ secrets.DISCORD_FLESH_AND_STEEL_WEBHOOK }}
          TIME: "6:30 PM"

      - name: send notification to covid
        shell: bash
        run: |
          echo "date is ${{ needs.jobs.config.outputs.COVID_DATE }}"
          echo "time is $TIME"
          docker run -e WEBHOOK=$WEBHOOK -e NEXT_DATE="$${{ needs.jobs.config.outputs.COVID_DATE }}" -e NEXT_TIME="$TIME" mdlopresti/scheduled_discord_messages:specific
        env:
          WEBHOOK: ${{ secrets.DISCORD_COVID_WEBHOOK }}
          TIME: "5:30 PM"