name: scheduled message sending

on:
  schedule:
    - cron: 0 16 * * 3
  workflow_dispatch:

jobs:
  notification:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Determine next session dates
        run: |
          $startdate = [datetime]"10/7/2020 00:00"
          Write-Host "start is $startdate"
          $nextsession = get-date -Hour 0 -Minute 0 -Second 0
          do {
            $nextsession = $nextsession.AddDays(1)
          } until ($nextsession.DayOfWeek -eq "Wednesday")

          Write-Host "The next wednesday is $nextsession"
          $time = New-TimeSpan -start $startdate -end $enddate
          if (($time.Days/14) -match '.5') {
            $FleshAndSteel = $nextsession.ToString("yyyy MM dd")
            $Covid = $nextsession.addDays(7).ToString("yyyy MM dd")
            Write-Host "::set-output name=FLESH_AND_STEEL::$FleshAndSteel"
            Write-Host "::set-output name=COVID::$Covid"
            Write-Host "Flesh and Steel this week"
          } else {
            $FleshAndSteel = $nextsession.addDays(7).ToString("yyyy MM dd")
            $Covid = $nextsession.ToString("yyyy MM dd")
            Write-Host "::set-output name=FLESH_AND_STEEL::$FleshAndSteel"
            Write-Host "::set-output name=COVID::$Covid"
            Write-Host "Unnamed covid campaign this week"
          }
        id: next_session_dates

      - name: send notifications
        run: |
          docker run -e WEBHOOK=$env:DISCORD_FLESH_AND_STEEL_WEBHOOK -e NEXT_DATE=$env:FLESH_AND_STEEL_DATE -e NEXT_TIME=$env:FLESH_AND_STEEL_TIME mdlopresti/scheduled_discord_messages:specific
          docker run -e WEBHOOK=$env:DISCORD_COVID_WEBHOOK -e NEXT_DATE=$env:COVID_DATE -e NEXT_TIME=$env:COVID_TIME mdlopresti/scheduled_discord_messages:specific
        env:
          DISCORD_FLESH_AND_STEEL_WEBHOOK: ${{ secrets.DISCORD_FLESH_AND_STEEL_WEBHOOK }}
          DISCORD_COVID_WEBHOOK: ${{ secrets.DISCORD_COVID_WEBHOOK }}
          FLESH_AND_STEEL_DATE: ${{ steps.next_session_dates.outputs.FLESH_AND_STEEL }}
          FLESH_AND_STEEL_TIME: "6:30 PM"
          COVID_DATE: ${{ steps.next_session_dates.outputs.COVID }}
          COVID_TIME: "5:30 PM"
