name: scheduled message sending

on:
  schedule:
    - cron: 0 16 * * 3
  workflow_dispatch:

jobs:
  config:
    runs-on: windows-latest
    steps:
      - name: Determine next session dates/times
        run: |
          $startdate = [datetime]"10/7/2020 00:00"
          Write-Host "start is $startdate"
          $nextsession = get-date -Hour 0 -Minute 0 -Second 0
          do {
            $nextsession = $nextsession.AddDays(1)
          } until ($nextsession.DayOfWeek -eq "Wednesday")

          Write-Host "The next wednesday is $nextsession"
          $time = New-TimeSpan -start $startdate -end $nextsession
          if (($time.Days/14) -match '.5') {
            $FleshAndSteel = $nextsession.ToString("yyyy MM dd")
            $Covid = $nextsession.addDays(7).ToString("yyyy MM dd")
            Write-Host "::set-output name=FLESH_AND_STEEL::$FleshAndSteel"
            Write-Host "::set-output name=COVID::$Covid"
          } else {
            $FleshAndSteel = $nextsession.addDays(7).ToString("yyyy MM dd")
            $Covid = $nextsession.ToString("yyyy MM dd")
            Write-Host "::set-output name=FLESH_AND_STEEL::$FleshAndSteel"
            Write-Host "::set-output name=COVID::$Covid"
          }
          Write-Host "FLESH_AND_STEEL_DATE = $FleshAndSteel"
          Write-Host "COVID_DATE = $Covid"
        id: next_session_dates

    outputs:
      FLESH_AND_STEEL_DATE: ${{ steps.next_session_dates.outputs.FLESH_AND_STEEL }}
      COVID_DATE: ${{ steps.next_session_dates.outputs.COVID }}

  notifications:
    needs: config
    runs-on: ubuntu-20.04
    steps:
      - name: send notifications
        run: |
          docker run -e WEBHOOK=$DISCORD_FLESH_AND_STEEL_WEBHOOK -e NEXT_DATE='$FLESH_AND_STEEL_DATE' -e NEXT_TIME='$FLESH_AND_STEEL_TIME' mdlopresti/scheduled_discord_messages:specific
          docker run -e WEBHOOK=$DISCORD_COVID_WEBHOOK -e NEXT_DATE='$COVID_DATE' -e NEXT_TIME='$COVID_TIME' mdlopresti/scheduled_discord_messages:specific
        env:
          DISCORD_FLESH_AND_STEEL_WEBHOOK: ${{ secrets.DISCORD_FLESH_AND_STEEL_WEBHOOK }}
          DISCORD_COVID_WEBHOOK: ${{ secrets.DISCORD_COVID_WEBHOOK }}
          FLESH_AND_STEEL_DATE: ${{ needs.jobs.config.outputs.FLESH_AND_STEEL_DATE }}
          FLESH_AND_STEEL_TIME: "6:30 PM"
          COVID_DATE: ${{ needs.jobs.config.outputs.COVID_DATE }}
          COVID_TIME: "5:30 PM"